### PR TITLE
JS-46: feat(tos): add support to filter by ToS

### PR DESCRIPTION
**Pull request by fooker**
# External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/JS-46

### CODE REVIEW

**Review by RangerRick — APPROVED** [review]
FYI this is still marked as draft, but looks pretty straightforward to me. 👍

**Comment by fooker** [comment]
> FYI this is still marked as draft, but looks pretty straightforward to me. +1

It's intended. There are more changes to come for the ToS feature which I want to bundle in a single request.

**Review by RangerRick — APPROVED** [review]
looks pretty straightforward to me

**Comment by RangerRick** [comment]
@fooker @swachter is there anything else you want to do for this, or should we merge it, so we can get a release out that Helm can point at?

**Comment by fooker** [comment]
> @fooker @swachter is there anything else you want to do for this, or should we merge it, so we can get a release out that Helm can point at?

LGTM

**Pull request merged**
